### PR TITLE
fix(config): read additional whitelist hosts from config

### PR DESCRIPTION
**Pull request by jmalins**
Patch to read whiteListHosts from config sources in addition to the default of collectorApiUrl. PR tries to follow your style as best as possible.

*Rationale:* 
On AWS, the Amazon SDK uses a small daemon running on a local network interface to serve up machine-level temporary credentials. These calls are picked up by trace. They exist on every microservice running on EC2, but don't add information to the topology. I'd like to exclude calls to 169.254.169.254. 

screen shot 2016-05-30 at 07 44 59

PS. I like what you guys are building... pretty slick so far.
-Jeff

### CODE REVIEW

**Comment by gergelyke** [comment]
Hello @jmalins !

Thanks for the contribution! Will get back to you shortly on this :)

G

**Comment by gergelyke** [comment]
Looks great! would you be ok with the following? I will move it back to our master, with a small change:

* rename `whiteListHosts` to `ignoreOutgoingHosts`, so it would fit into the current naming of rules: https://trace-docs.risingstack.com/docs/advanced-usage

**Comment by jmalins** [comment]
Thanks for the fast response!
No problem, `ignoreOutgoingHosts` is much clearer. Should I update the PR or will you handle it in the merge?

**Comment by gergelyke** [comment]
If it is ok for you, I will just cherry pick stuff, and push it to our internal repo first - as well as adding this minor change. I can land the fix for it early tomorrow.
Sounds good?

**Comment by jmalins** [comment]
Perfect. 
There's no huge rush on my side. I was looking for a distraction yesterday and thought I'd contribute something that'd make my use case slightly nicer.

**Comment by gergelyke** [comment]
It just landed as 2.15.0 :)

**Comment by jmalins** [comment]
Working perfectly. Thanks!

**Pull request closed without merging**
